/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '@angular/common';
import * as import2 from '../../../../src/app/components/college-details.component';
import * as import3 from '../../../../src/app/services/education.service';
import * as import4 from '@angular/router';
const styles_CollegeDetailsComponent:any[] = ([] as any[]);
export const RenderType_CollegeDetailsComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_CollegeDetailsComponent,
  data: {}
}
);
function View_CollegeDetailsComponent_1(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'p',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),[
      'ID: ',
      ''
    ]
    ))
  ]
  ,(null as any),(ck,v) => {
    var co:any = v.component;
    const currVal_0:any = co.college.id;
    ck(v,1,0,currVal_0);
  });
}
export function View_CollegeDetailsComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['Details for College'])),
    (l()(),import0.ɵted((null as any),['\n'])),
    (l()(),import0.ɵand(8388608,(null as any),(null as any),1,(null as any),View_CollegeDetailsComponent_1)),
    import0.ɵdid(8192,(null as any),0,import1.NgIf,[
      import0.ViewContainerRef,
      import0.TemplateRef
    ]
      ,{ngIf: [
        0,
        'ngIf'
      ]
    },(null as any)),
    (l()(),import0.ɵted((null as any),['\n'])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'button',[
      [
        'class',
        'btn btn-default'
      ]
      ,
      [
        'type',
        'button'
      ]

    ]
      ,(null as any),[[
        (null as any),
        'click'
      ]
    ],(v,en,$event) => {
      var ad:boolean = true;
      var co:import2.CollegeDetailsComponent = v.component;
      if (('click' === en)) {
        const pd_0:any = ((<any>co.goBack()) !== false);
        ad = (pd_0 && ad);
      }
      return ad;
    },(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['Back to Education']))
  ]
  ,(ck,v) => {
    var co:import2.CollegeDetailsComponent = v.component;
    const currVal_0:any = co.college;
    ck(v,4,0,currVal_0);
  },(null as any));
}
function View_CollegeDetailsComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'college-details',([] as any[]),(null as any),(null as any),(null as any),View_CollegeDetailsComponent_0,RenderType_CollegeDetailsComponent)),
    import0.ɵdid(57344,(null as any),0,import2.CollegeDetailsComponent,[
      import3.EducationService,
      import4.ActivatedRoute,
      import4.Router
    ]
    ,(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const CollegeDetailsComponentNgFactory:import0.ComponentFactory<import2.CollegeDetailsComponent> = import0.ɵccf('college-details',import2.CollegeDetailsComponent,View_CollegeDetailsComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL0FuZHJld1N0YXJyL0RvY3VtZW50cy92c0NvZGUvUGVyc29uYWwgV2Vic2l0ZS9zcmMvYXBwL2NvbXBvbmVudHMvY29sbGVnZS1kZXRhaWxzLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9BbmRyZXdTdGFyci9Eb2N1bWVudHMvdnNDb2RlL1BlcnNvbmFsIFdlYnNpdGUvc3JjL2FwcC9jb21wb25lbnRzL2NvbGxlZ2UtZGV0YWlscy5jb21wb25lbnQudHMiLCJuZzovLy9Vc2Vycy9BbmRyZXdTdGFyci9Eb2N1bWVudHMvdnNDb2RlL1BlcnNvbmFsIFdlYnNpdGUvc3JjL2FwcC90ZW1wbGF0ZXMvY29sbGVnZS1kZXRhaWxzLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vVXNlcnMvQW5kcmV3U3RhcnIvRG9jdW1lbnRzL3ZzQ29kZS9QZXJzb25hbCBXZWJzaXRlL3NyYy9hcHAvY29tcG9uZW50cy9jb2xsZWdlLWRldGFpbHMuY29tcG9uZW50LnRzLkNvbGxlZ2VEZXRhaWxzQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGgxPkRldGFpbHMgZm9yIENvbGxlZ2U8L2gxPlxuPHAgKm5nSWY9XCJjb2xsZWdlXCI+SUQ6IHt7Y29sbGVnZS5pZH19PC9wPlxuPGJ1dHRvbiB0eXBlPVwiYnV0dG9uXCIgXG4gICAgICAgIChjbGljayk9XCJnb0JhY2soKVwiIFxuICAgICAgICBjbGFzcz1cImJ0biBidG4tZGVmYXVsdFwiPkJhY2sgdG8gRWR1Y2F0aW9uPC9idXR0b24+IiwiPGNvbGxlZ2UtZGV0YWlscz48L2NvbGxlZ2UtZGV0YWlscz4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O0lDQ0E7SUFBbUI7TUFBQTtNQUFBO0lBQUE7SUFBQTs7OztJQUFBO0lBQUE7Ozs7O0lBRG5CO0lBQUk7SUFBd0I7SUFDNUI7Z0JBQUE7OztJQUFBO09BQUE7UUFBQTtRQUFBO01BQUE7SUFBQTtJQUF5QztJQUN6QztNQUFBO1FBQUE7UUFBQTtNQUFBOztNQUFBO1FBQUE7UUFBQTtNQUFBOztJQUFBO09BQUE7UUFBQTtRQUFBO01BQUE7SUFBQTtNQUFBO01BQUE7TUFDUTtRQUFBO1FBQUE7TUFBQTtNQURSO0lBQUE7SUFFZ0M7Ozs7SUFIN0I7SUFBSCxTQUFHLFNBQUg7Ozs7O0lDREE7Z0JBQUE7Ozs7SUFBQTtLQUFBOzs7SUFBQTs7OyJ9
