/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '../styles/home.component.css.shim.ngstyle';
import * as import1 from '@angular/core';
import * as import2 from '../../../../src/app/components/home.component';
const styles_HomeComponent:any[] = [import0.styles];
export const RenderType_HomeComponent:import1.RendererType2 = import1.ɵcrt({
  encapsulation: 0,
  styles: styles_HomeComponent,
  data: {}
}
);
export function View_HomeComponent_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['Software Developer'])),
    (l()(),import1.ɵted((null as any),['\n'])),
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'h2',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['Andrew Starr'])),
    (l()(),import1.ɵted((null as any),['\n'])),
      (l()(),import1.ɵeld(0,(null as any),(null as any),9,'div',[[
        'id',
        'special'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['\n    '])),
      (l()(),import1.ɵeld(0,(null as any),(null as any),1,'h3',[[
        'id',
        'logic'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['Logical'])),
    (l()(),import1.ɵted((null as any),[' \n    '])),
      (l()(),import1.ɵeld(0,(null as any),(null as any),0,'span',[[
        'id',
        'pipe'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['\n    '])),
      (l()(),import1.ɵeld(0,(null as any),(null as any),1,'h3',[[
        'id',
        'creative'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['Creative'])),
    (l()(),import1.ɵted((null as any),['\n']))
  ]
  ,(null as any),(null as any));
}
function View_HomeComponent_Host_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'home-page',([] as any[]),(null as any),(null as any),(null as any),View_HomeComponent_0,RenderType_HomeComponent)),
    import1.ɵdid(24576,(null as any),0,import2.HomeComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const HomeComponentNgFactory:import1.ComponentFactory<import2.HomeComponent> = import1.ɵccf('home-page',import2.HomeComponent,View_HomeComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL0FuZHJld1N0YXJyL0RvY3VtZW50cy92c0NvZGUvUGVyc29uYWwgV2Vic2l0ZS9zcmMvYXBwL2NvbXBvbmVudHMvaG9tZS5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvQW5kcmV3U3RhcnIvRG9jdW1lbnRzL3ZzQ29kZS9QZXJzb25hbCBXZWJzaXRlL3NyYy9hcHAvY29tcG9uZW50cy9ob21lLmNvbXBvbmVudC50cyIsIm5nOi8vL1VzZXJzL0FuZHJld1N0YXJyL0RvY3VtZW50cy92c0NvZGUvUGVyc29uYWwgV2Vic2l0ZS9zcmMvYXBwL3RlbXBsYXRlcy9ob21lLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vVXNlcnMvQW5kcmV3U3RhcnIvRG9jdW1lbnRzL3ZzQ29kZS9QZXJzb25hbCBXZWJzaXRlL3NyYy9hcHAvY29tcG9uZW50cy9ob21lLmNvbXBvbmVudC50cy5Ib21lQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGgxPlNvZnR3YXJlIERldmVsb3BlcjwvaDE+XG48aDI+QW5kcmV3IFN0YXJyPC9oMj5cbjxkaXYgaWQ9XCJzcGVjaWFsXCI+XG4gICAgPGgzIGlkPVwibG9naWNcIj5Mb2dpY2FsPC9oMz4gXG4gICAgPHNwYW4gaWQ9XCJwaXBlXCI+PC9zcGFuPlxuICAgIDxoMyBpZD1cImNyZWF0aXZlXCI+Q3JlYXRpdmU8L2gzPlxuPC9kaXY+IiwiPGhvbWUtcGFnZT48L2hvbWUtcGFnZT4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7OztJQ0FBO0lBQUk7SUFBdUI7SUFDM0I7SUFBSTtJQUFpQjtNQUNyQjtRQUFBO1FBQUE7TUFBQTtJQUFBO0lBQWtCO01BQ2Q7UUFBQTtRQUFBO01BQUE7SUFBQTtJQUFlO0lBQVk7TUFDM0I7UUFBQTtRQUFBO01BQUE7SUFBQTtJQUF1QjtNQUN2QjtRQUFBO1FBQUE7TUFBQTtJQUFBO0lBQWtCO0lBQWE7Ozs7OztJQ0xuQztnQkFBQTs7OzsifQ==
