/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['div#img-closeups[_ngcontent-%COMP%] { margin-bottom: 5%; }\n\n@media only screen and (min-width: 768px) {\n    h1[_ngcontent-%COMP%] { padding-top: 20px; }\n    div#img-closeups[_ngcontent-%COMP%] { margin-bottom: 3.5%;}\n}\n\n@media only screen and (min-width: 992px) {\n    h1[_ngcontent-%COMP%] { padding-top: 35px; }\n    div#img-closeups[_ngcontent-%COMP%] { margin-bottom: 2%; }\n}\n\n@media only screen and (min-width: 1200px) {\n    h1[_ngcontent-%COMP%] { padding-top: 50px; }\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL0FuZHJld1N0YXJyL0RvY3VtZW50cy92c0NvZGUvUGVyc29uYWwgV2Vic2l0ZS9zcmMvYXBwL3N0eWxlcy9hYm91dC1tZS5jb21wb25lbnQuY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL0FuZHJld1N0YXJyL0RvY3VtZW50cy92c0NvZGUvUGVyc29uYWwgV2Vic2l0ZS9zcmMvYXBwL2NvbXBvbmVudHMvYWJvdXQtbWUuY29tcG9uZW50LnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
