/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */ export var styles = ['div#img-closeups[_ngcontent-%COMP%] { margin-bottom: 5%; }\n\n@media only screen and (min-width: 768px) {\n    h1[_ngcontent-%COMP%] { padding-top: 20px; }\n    div#img-closeups[_ngcontent-%COMP%] { margin-bottom: 3.5%;}\n}\n\n@media only screen and (min-width: 992px) {\n    h1[_ngcontent-%COMP%] { padding-top: 35px; }\n    div#img-closeups[_ngcontent-%COMP%] { margin-bottom: 2%; }\n}\n\n@media only screen and (min-width: 1200px) {\n    h1[_ngcontent-%COMP%] { padding-top: 50px; }\n}'];
//# sourceMappingURL=about-me.component.css.shim.ngstyle.js.map