/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['h1[_ngcontent-%COMP%] { text-align: center; }\nh4[_ngcontent-%COMP%] { text-align: right; }\n\np[_ngcontent-%COMP%] {\n    padding-left: 3px;\n    padding-top: 3px;\n    font-size: 1.1em;\n    margin: 0;\n}\n\n@media only screen and (min-width: 768px) {\n    p[_ngcontent-%COMP%] { font-size: 1.6em; }\n}\n\n@media only screen and (min-width: 992px) {\n    p[_ngcontent-%COMP%] { \n        font-size: 2.1em; \n        padding-top: 1px;\n    }\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL0FuZHJld1N0YXJyL0RvY3VtZW50cy92c0NvZGUvUGVyc29uYWwgV2Vic2l0ZS9zcmMvYXBwL3N0eWxlcy9lZHVjYXRpb24uY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9BbmRyZXdTdGFyci9Eb2N1bWVudHMvdnNDb2RlL1BlcnNvbmFsIFdlYnNpdGUvc3JjL2FwcC9jb21wb25lbnRzL2VkdWNhdGlvbi5jb21wb25lbnQudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
