/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */ export var styles = ['h1[_ngcontent-%COMP%] { text-align: center; }\nh4[_ngcontent-%COMP%] { text-align: right; }\n\np[_ngcontent-%COMP%] {\n    padding-left: 3px;\n    padding-top: 3px;\n    font-size: 1.1em;\n    margin: 0;\n}\n\n@media only screen and (min-width: 768px) {\n    p[_ngcontent-%COMP%] { font-size: 1.6em; }\n}\n\n@media only screen and (min-width: 992px) {\n    p[_ngcontent-%COMP%] { \n        font-size: 2.1em; \n        padding-top: 1px;\n    }\n}'];
//# sourceMappingURL=education.component.css.shim.ngstyle.js.map