/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['img#logo[_ngcontent-%COMP%] {\n    width: 100px;\n    height: 75px;\n    margin-top: 3%;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL0FuZHJld1N0YXJyL0RvY3VtZW50cy92c0NvZGUvUGVyc29uYWwgV2Vic2l0ZS9zcmMvYXBwL3N0eWxlcy9qb2ItZGV0YWlscy5jb21wb25lbnQuY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL0FuZHJld1N0YXJyL0RvY3VtZW50cy92c0NvZGUvUGVyc29uYWwgV2Vic2l0ZS9zcmMvYXBwL2NvbXBvbmVudHMvam9iLWRldGFpbHMuY29tcG9uZW50LnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
