/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */ export var styles = ['img#logo[_ngcontent-%COMP%] {\n    width: 100px;\n    height: 75px;\n    margin-top: 3%;\n}'];
//# sourceMappingURL=job-details.component.css.shim.ngstyle.js.map