/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = [''];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL0FuZHJld1N0YXJyL0RvY3VtZW50cy92c0NvZGUvUGVyc29uYWwgV2Vic2l0ZS9zcmMvYXBwL3N0eWxlcy9wcm9qZWN0LWRldGFpbHMuY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9BbmRyZXdTdGFyci9Eb2N1bWVudHMvdnNDb2RlL1BlcnNvbmFsIFdlYnNpdGUvc3JjL2FwcC9jb21wb25lbnRzL3Byb2plY3QtZGV0YWlscy5jb21wb25lbnQudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
