/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */ export var styles = ['h1[_ngcontent-%COMP%] { text-align: center; }\n\n.badge[_ngcontent-%COMP%] {\n    margin: 3px;\n    color: rgba(180, 0, 0, 0.75);\n}\n\n@media only screen and (min-width: 768px) {\n    .badge[_ngcontent-%COMP%] { font-size: 1.1em; }\n}\n\n@media only screen and (min-width: 992px) {\n    .badge[_ngcontent-%COMP%] { \n        font-size: 1.3em; \n        margin: 7px;\n    }\n}'];
//# sourceMappingURL=work-samples.component.css.shim.ngstyle.js.map