/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['h1[_ngcontent-%COMP%] { text-align: center; }\n\n.badge[_ngcontent-%COMP%] {\n    margin: 3px;\n    color: rgba(180, 0, 0, 0.75);\n}\n\n@media only screen and (min-width: 768px) {\n    .badge[_ngcontent-%COMP%] { font-size: 1.1em; }\n}\n\n@media only screen and (min-width: 992px) {\n    .badge[_ngcontent-%COMP%] { \n        font-size: 1.3em; \n        margin: 7px;\n    }\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL0FuZHJld1N0YXJyL0RvY3VtZW50cy92c0NvZGUvUGVyc29uYWwgV2Vic2l0ZS9zcmMvYXBwL3N0eWxlcy93b3JrLXNhbXBsZXMuY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9BbmRyZXdTdGFyci9Eb2N1bWVudHMvdnNDb2RlL1BlcnNvbmFsIFdlYnNpdGUvc3JjL2FwcC9jb21wb25lbnRzL3dvcmstc2FtcGxlcy5jb21wb25lbnQudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
